# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startxlab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
