# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startxlab_app', '0004_commentsmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentsmodel',
            table='comments',
        ),
    ]
