# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startxlab_app', '0007_auto_20191217_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='comment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
