# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startxlab_app', '0008_auto_20191217_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=8, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
